development:
  mailer_sender: 'info@oandatrader-development.herokuapp.com'
backtest:
  mailer_sender: 'info@oandatrader-backtest.herokuapp.com'
test:
  mailer_sender: 'info@oandatrader-test.herokuapp.com'
production:
  mailer_sender: 'info@oandatrader.herokuapp.com'
staging:
  mailer_sender: 'info@oandatrader-staging.herokuapp.com'
